# Site settings
title: bestk1ng
email: bestk1ngarthur@aol.com
description: > 
  Light beautifull description from the future
baseurl: "" 
url: "http://bestk1ng.ru"
twitter_username: bestk1ngarthur
github_username:  bestk1ngarthur
vk_username:      bestk1ngarthur

# Build settings
markdown: kramdown
